RDDJS.skills = {
    "general":[
       -4,
       [
          'climbing',
          'cooking',
          'dance',
          'discretion',
          'drawing',
          'jumping',
          'running',
          'seduction',
          'singing',
          'tinkering',
          'vigilance'
       ]
    ],
    "arts":[
       -11,
       [
          'acrobatics',
          'gaming',
          'jewelrysmithing',
          'juggling',
          'leatherwork',
          'locksmithing',
          'metalwork',
          'navigation',
          'surgery',
          'swimming'
       ]
    ],
    "specialized":[
       -8,
       [
          'acting',
          'carpentry',
          'commerce',
          'disguise',
          'masonry',
          'music',
          'pickpocket',
          'riding',
          'city-survival',
          'outdoor-survival',
          'artic',
          'desert',
          'forest',
          'mountain',
          'swamp',
          'underground'
       ]
    ],
    "sciences":[
       -11,
       [
          'alchemy',
          'astrology',
          'botany',
          'legends',
          'medicine',
          'writing',
          'zoology'
       ]
    ],
    "draconic":[
       -11,
       [
          'oneiros',
          'hypnos',
          'narcos',
          'thanatos'
       ]
    ],
    "melee":[
       -6,
       [
          '1-handed-axe',
          '2-handed-axe',
          'dagger',
          'dodging',
          'hand-to-hand',
          'lance',
          '1-handed-mace',
          '2-handed-mace',
          'shield',
          '1-handed-sword',
          '2-handed-sword',
          'flail'
       ]
    ],
    "mt":[
       -8,
       [
          'bow',
          'crossbow',
          'knife',
          'hand-axe',
          'javelin',
          'lasso',
          'whip'
       ]
    ]
 }