RDDJS.spells = {
    "oneiros" : [
        ['Annihilation', 'Lake', 'D-13', 'd12'],
        ['Anti-Magic', 'Plains', 'D-2', 'd1+'],
        ['Clamors', 'City', 'D-2', 'd1+'],
        ['Cold', 'Waste', 'D-4', 'd1+'],
        ['Darkness', 'Chasm', 'D-4', 'd3'],
        ['Dream Skiff', 'Lake', 'D-8', 'd5+'],
        ['Flying Bubble', 'Swamp', 'D-10', 'd6+'],
        ['Fog, Forest', 'D-3', 'd1+'],
        ['Heat', 'City', 'D-4', 'd1+'],
        ['Illusionary Animal','Forest','D-4','d4'],
        ['Illusionary Humanoid','City','D-6','d2+'],
        ['Illusionary Terrain','Chasm','D-4','d4'],
        ['Immaterial Bridge','Bridge','D-6','d2+'],
        ['Lantern','City','D-3','d2'],
        ['Light','Plains','D-4','d3'],
        ['Magnetism','Mountain','D-8','d3+'],
        ['Mirrors','Sanctuary','D-5','d5'],
        ['Plant Growth','Forest','D-6','d5'],
        ['Quiet','Necropolis','D-3','d4'],
        ['Shield','Chasm','D-7','d6'],
        ['Silence','Desert','D-2','d4'],
        ['Teleportation','Hills','D-11','d9'],
        ['Weightlessness','Swamp','D-4','d2+'],
        ['Red Transmutation','City','D-5','d5'],
        ['Orange Transmutation','Sanctuary','D-6','d5'],
        ['Yellow Transmutation','Desert','D-7','d5'],
        ['Green Transmutation','Forest','D-8','d5'],
        ['Blue Transmutation','Mountain','D-9','d5'],
        ['Violet Transmutation','Chasm','D-10','d5'],
        ['Air to Fire','Waste','D-10','d6'],
        ['Air to Water','City','D-8','d6'],
        ['Earth to Air','Lake','D-8','d6'],
        ['Earth to Metal','Chasm','D-6','d4'],
        ['Earth to Water','Forest','D-6','d4'],
        ['Earth to Wood','Plains','D-4','d2'],
        ['Fire to Air','Waste','D-4','d2'],
        ['Fire to Earth','Desert','D-6','d4'],
        ['Fire to Metal','Sanctuary','D-6','d4'],
        ['Fire to Water','City','D-6','d4'],
        ['Fire to Wood','Hills','D-6','d4'],
        ['Metal to Air','Lethe','D-8','d6'],
        ['Metal to Earth','Plains','D-6','d4'],
        ['Metal to Fire','Lake','D-8','d6'],
        ['Metal to Wood','Hills','D-6','d4'],
        ['Metal to Water','Lethe','D-8','d6'],
        ['Water to Air','Desert','D-4','d2'],
        ['Water to Earth','Bridge','D-6','d4'],
        ['Water to Fire','Mountain','D-8','d6'],
        ['Water to Metal','Chasm','D-6','d4'],
        ['Water to Wood','Forest','D-4','d2'],
        ['Wood to Air','Swamp','D-8','d6'],
        ['Wood to Earth','Necropolis','D-4','d2'],
        ['Wood to Fire','Desert','D-6','d4'],
        ['Wood to Metal','Mountain','D-6','d4'],
        ['Wood to Water','Sanctuary','D-6','d4'],
        ['Transparent Earth','Hills','D-4','d4'],
        ['Transparent Metal','Chasm','D-4','d4'],
        ['Transparent Wood','City','D-4','d4'],
        ['Buoy','Bridge','D-3','d3+'],
        ['Hauberk of Oneiros','Lethe','D-8','d7+'],
        ['Mantle','Sanctuary','D-3','d1+'],
        ['Radiance','Waste','D-3','d2+'],
        ['Red Invulnerability','Hills','D-6','d2'],
        ['Orange Invulnerability','Desert','D-7','d3'],
        ['Yellow Invulnerability','Mountain','D-8','d4'],
        ['Green Invulnerability','Chasm','D-10','d5'],
        ['Blue Invulnerability','Lake','D-12','d6'],
        ['Violet Invulnerability','Swamp','D-14','d8'],
        ['Counterspell','Variable',' var.','var.'],
        ['Counterspell Self','Variable','D-4','d2'],
        ['Enlarge Zone','Variable','D-4','d4'],
        ['Permanent Zone*','Variable','D-13','d13'],
        ['Detect Aura','Sanctuary','D-3','d1'],
        ['Read Aura','Sanctuary','D-3','d3']
    ],

    "hypnos" : [
        ['Amnesia','Lethe','D-8','d6+'],
        ['Confusion','Waste','D-4','d4'],
        ['Dreamlessness','Waste','D-7','d4+'],
        ['Fatigue','Necropolis','D-7','d5'],
        ['Fear','Necropolis','D-5','d5'],
        ['Lash','Chasm','D-6','d1+'],
        ['Nonaggression','Sanctuary','D-4','d3'],
        ['Respite','City','D-3','d2+'],
        ['Serenity','Hills','D-3','d3+'],
        ['Sleep','Swamp','D-9','d1+'],
        ['Sleep of Hypnos','Swamp','D-11','d8'],
        ['Stumble','Plains','D-6','d5'],
        ['Suggestion','Desert','D-9','d3+'],
        ['Drum of Hypnos','Hills','D-5','d4'],
        ['Invisibility','Lethe','D-10','d8'],
        ['Metamorphosis','Chasm','D-8','d6'],
        ['Nose of Hypnos','Plains','D-4','d3'],
        ['Tongue of Hynos','City','D-3','d2'],
        ['Transfiguration','Mountain','D-6','d4'],
        ['Black Ink of Hypnos','Lethe','D-11','d2+'],
        ['Harp of Hypnos','Mountain','D-4','d1+'],
        ['Incense of Hypnos','Necropolis','D-6','d6'],
        ['Invoke Image','Sanctuary','D-6','d1+'],
        ['Invoke Presence','Necropolis','D-9','d1+'],
        ['Invoke Voice','City','D-6','d1+'],
        ['Mirror of Hypnos','Necropolis','D-5','d1+'],
        ['Voice of Hypnos','Desert','D-4','d4'],
        ['Courser Herd','H4','D-8','d7'],
        ['Gremlin','E1','D-5','d4'],
        ['Noneshallpass','M1','D-8','d7'],
        ['Sord Warrior','D13','D-8','d7'],
        ['Turmid Warrior','C8','D-8','d7'],
        ['Wary Murder','B2','D-8','d7'],
        ['Counterspell','Variable',' var.','var.'],
        ['Counter Own Illusions ','Variable','D-4','d2'],
        ['Conjure Lethe','Lake','D-4','d4'],
        ['Detect Aura','Sanctuary','D-3','d1'],
        ['Read Aura','Sanctuary','D-3','d3']
    ],

    "narcos" : [
        ['Alliance','Bridge','D-4','d4'],
        ['Autonomy**','Lake','D-10','d10'],
        ['Enchantment','City','D-4','d1+'],
        ['Individuality','Desert','D-4','d4'],
        ['Mastery','Lethe','D-7','d7'],
        ['Permanence*','Sanctuary','D-5','d5'],
        ['Purification','Necropolis','D-4','d4'],
        ['Restoration*','City','D-6','d1+'],
        ['Scale of Activity*','Waste','D-9','d7'],
        ['Scale of Efficiency*','Mountain','D-8','d7'],
        ['From Blades*','Lake','D-10','d8'],
        ['From Claw & Fang* ','Swamp','D-10','d8'],
        ['From Disease*','City','D-6','d4'],
        ['From Fire*','Desert','D-6','d4'],
        ['From Magic*','Sanctuary','D-8','d6'],
        ['From Poison*','Forest','D-6','d4'],
        ['From Projectiles*','Chasm','D-8','d6'],
        ['Melimnod’s Kettle*','E5','D-9','d9'],
        ['Well of Dreams*','Lake','D-8','d8'],
        ['Counterspell','Variable',' var.','var.'],
        ['Detect Aura','Sanctuary','D-3','d1'],
        ['Read Aura','Sanctuary','D-3','d3']
    ],

    "thanatos" : [
        ['Body Possession','Swamp','D-9','d2+'],
        ['Spirit Possession','Lake','D-9','d2+'],
        ['Beastform','Lethe','D-10','d10'],
        ['Blindness','City','D-8','d2+'],
        ['Disease','Waste','D-11','d5+'],
        ['Deafness','Chasm','D-6','d2+'],
        ['Interdiction','Desert','D-7','d7'],
        ['Nightmare','Mountain','D-5','d5'],
        ['Task','Forest','D-8','d8'],
        ['Beastform Self','Forest','D-7','d7'],
        ['Fist of Thanatos','Plains','D-6','d1+'],
        ['Grotesque','Lethe','D-8','d1+'],
        ['Necromantic Fear','Lake','D-9','d1+'],
        ['Putrescence','Swamp','D-8','d1+'],
        ['Thanateye','Necropolis','D-5','d1+'],
        ['Animate Skeleton','Necropolis','D-9','d1+'],
        ['Animate Zombie','Necropolis','D-7','d1+'],
        ['Summon Despair','Waste','D-7','d7'],
        ['Summon Fear','Chasm','D-7','d7'],
        ['Summon Hate','Swamp','D-7','d7'],
        ['Speak with Dead','Desert','D-6','d1+'],
        ['Speak with Skull ','Bridge','D-4','d1+'],
        ['Claw of Thanatos*','Necropolis','D-8','d8'],
        ['Morbid Claw of Thanatos* ','Swamp','D-11','d11'],
        ['Murderblade**','G9','D-13','d13'],
        ['Detect Aura','Sanctuary','D-3','d1'],
        ['Read Aura','Sanctuary','D-3','d3']
    ]
}